/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    primary: '#007AFF',
    primaryText: '#FFFFFF',
    secondary: '#5856D6',
    secondaryText: '#FFFFFF',
    success: '#34C759',
    successText: '#FFFFFF',
    danger: '#FF3B30',
    dangerText: '#FFFFFF',
    warning: '#FF9500',
    warningText: '#FFFFFF',
    textPrimary: '#1f2937',
    textSecondary: '#6b7280',
    textTertiary: '#9ca3af',
    cardBackground: '#f9fafb',
    cardBorder: '#e5e7eb',
    cardShadow: '#000000',
    listItemBackground: '#ffffff',
    listItemHover: '#f3f4f6',
    listItemBorder: '#f3f4f6',
    modalBackground: '#ffffff',
    modalOverlay: 'rgba(0, 0, 0, 0.5)',
    modalBorder: '#e5e7eb',
    inputBackground: '#ffffff',
    inputBorder: '#d1d5db',
    inputPlaceholder: '#9ca3af',
    inputText: '#1f2937',
    buttonPrimary: '#007AFF',
    buttonSecondary: '#f3f4f6',
    buttonSecondaryText: '#374151',
    buttonBorder: '#d1d5db',
    buttonText: '#ffffff',
  },
  dark: {
    text: '#fff',
    background: '#000',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    primary: '#0A84FF',
    primaryText: '#FFFFFF',
    secondary: '#5E5CE6',
    secondaryText: '#FFFFFF',
    success: '#30D158',
    successText: '#FFFFFF',
    danger: '#FF453A',
    dangerText: '#FFFFFF',
    warning: '#FF9F0A',
    warningText: '#FFFFFF',
    textPrimary: '#f9fafb',
    textSecondary: '#d1d5db',
    textTertiary: '#9ca3af',
    cardBackground: '#1f2937',
    cardBorder: '#374151',
    cardShadow: '#000000',
    listItemBackground: '#1f2937',
    listItemHover: '#374151',
    listItemBorder: '#374151',
    modalBackground: '#1f2937',
    modalOverlay: 'rgba(0, 0, 0, 0.7)',
    modalBorder: '#374151',
    inputBackground: '#374151',
    inputBorder: '#4b5563',
    inputPlaceholder: '#9ca3af',
    inputText: '#f9fafb',
    buttonPrimary: '#0A84FF',
    buttonSecondary: '#374151',
    buttonSecondaryText: '#f9fafb',
    buttonBorder: '#4b5563',
    buttonText: '#ffffff',
  },
};
